<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<!-- xUnit v3 (рекомендовано для .NET 8+) -->
		<PackageReference Include="coverlet.collector" Version="8.0.1">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="1.0.0" />

		<!-- Visual Studio Test Explorer adapter (підтримує xUnit v3 і .NET 9) -->
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- Обов’язковий для dotnet test / VS Test Explorer -->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />

		<!-- Moq – стабільна версія, працює з .NET 9 -->
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebTechnologiesLab1\WebTechnologiesLab1.csproj" />
	</ItemGroup>

</Project>